
---
# tasks file for mysql

- name: Include OS-specific variables
  include_vars: "{{ ansible_os_family }}.yml"

- include: setup-RedHat.yml
  when: ansible_os_family == 'RedHat'

- include: setup-Debian.yml
  when: ansible_os_family == 'Debian'

- name: Create Mysql configuration file
  template: src="my.cnf.{{ ansible_os_family }}.j2" dest={{ mysql_conf_path }}

- name: Start Mysql Service
  service: name={{ mysql_service }} state=started enabled=yes

- name: Remove anonymous MySQL users
  action: mysql_user user="" host="{{ item }}" state="absent"
  with_items:
   - "{{ ansible_hostname }}"
   - "{{ ansible_fqdn }}"
   - localhost

- name: Secure MySQL installation / change root user password
  mysql_user: login_user=root
              login_password=''
              name=root
              password={{ MySQLPass | mandatory }}
              priv=*.*:ALL,GRANT
              host={{ item }}
  with_items:
        - "{{ ansible_hostname }}"
        - "{{ ansible_fqdn }}"
        - "%"
        - 127.0.0.1
        - ::1
        - localhost

- name: Restart Mysql Service
  service: name={{ mysql_service }} state=restarted
